branch: master
assignees: kryskool
branch_prefix: pyup/
label_prs: update

requirements:
  - test-requirements.txt:
    pin: True
  - requirements.txt:
    pin: True
  - docs-requirements.txt:
    pin: True
