dist: trusty
language: python
# sudo: required
install:
    #- pip install cryptography
    #- pip install coveralls
    - pip install codecov
    - python setup.py install
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
notifications:
  email: false
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'nightly'
jobs:
  allow_failures:
    - python: "nightly"
script:
    - py.test -s -v --cov=.
after_success:
    - codecov
    #- coveralls
