dist: trusty
language: python
# sudo: required
install:
    #- pip install cryptography
    #- pip install coveralls
    - pip install codecov
    - python setup.py install
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install Sphinx
notifications:
  email: false
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'nightly'
jobs:
  allow_failures:
    - python: "nightly"
script:
    - py.test -s -v --cov=.
after_success:
    - codecov
    - cd docs && make html
    #- coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/build/html/
  on:
    branch: master
